services:
  - type: web
    name: senegal-api-admin
    env: java
    plan: free
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/SenegalApiAdmin-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
    autoDeploy: true